name: 🗑 Wipe stale artifacts
on:
  schedule:
  - cron: 23 * * * *  # every hour

jobs:
  cleanup-artifacts:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 1 week  # Setting this to 0 will delete all artifacts
        skip-recent: 24
